# Generated by Django 5.0.7 on 2024-07-19 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciador_estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='senha',
            new_name='password',
        ),
    ]
